Support new cmake filenames
VisionSystemsInc/vsi_common pull request #409
Opened 2021-12-08 20:25 UTC by andyneff

Horray for random name changes!

2021-12-08 20:38 UTC, drewgilliam requested changes

2021-12-08 20:38 UTC, drewgilliam commented on linux/just_files/just_install_functions.bsh
> +  if meet_requirements ${cmake_ver} '<1.20'; then
`1.20` -> `3.20` ?

2021-12-09 15:37 UTC, drewgilliam requested changes

2021-12-09 15:46 UTC, andyneff commented on linux/just_files/just_install_functions.bsh
> +      if meet_requirements ${cmake_ver} '>=3.19'; then
Yep, sure can! Good catch

2021-12-09 15:49 UTC, drewgilliam approved these changes

2021-12-09 16:44 UTC, merged